export const figmaAssets = [
  {
    file: '/figma/injective-icon-white.svg',
    sourceNode: '19:32',
    width: 13,
    height: 13,
    intent: 'hero eyebrow icon',
    exportStatus: 'exported',
  },
  {
    file: '/figma/injective-token.svg',
    sourceNode: '19:117',
    width: 14,
    height: 14,
    intent: 'INJ reward icon',
    exportStatus: 'exported',
  },
  {
    file: '/figma/ninja-nft.png',
    sourceNode: '19:67',
    width: 48,
    height: 48,
    intent: 'hero portfolio avatar',
    exportStatus: 'figma-render-empty',
  },
  {
    file: '/figma/activity-injective-multivm-campaign.jpg',
    sourceNode: '19:108',
    width: 271,
    height: 152.44,
    intent: 'bounty cover',
    exportStatus: 'figma-render-empty',
  },
  {
    file: '/figma/activity-ninja-break-chill-building.png',
    sourceNode: '19:129',
    width: 271,
    height: 152.44,
    intent: 'bounty cover',
    exportStatus: 'figma-render-empty',
  },
  {
    file: '/figma/event-insight.png',
    sourceNode: '19:144',
    width: 271,
    height: 152.44,
    intent: 'bounty cover',
    exportStatus: 'figma-render-empty',
  },
  {
    file: '/figma/activity-ninja-api-forge.png',
    sourceNode: '19:159',
    width: 271,
    height: 152.44,
    intent: 'bounty cover',
    exportStatus: 'figma-render-empty',
  },
] as const;
