import type { Bounty } from "./types";

export const bounties: Bounty[] = [
  {
    slug: "iasset-price-widget", title: "Build an iAsset price widget", summary: "Build a reusable price widget for Injective iAssets.", descriptionMarkdown: "Build a reusable price widget for Injective iAssets that product teams can embed without recreating pricing logic. The widget should present current price data clearly and handle loading and unavailable states gracefully.", category: "Dev", status: "active", reward: { amount: 500, currency: "INJ" }, sponsor: "Injective", deadline: "D-7", deadlineDetail: "July 14, 2026 at 23:59 UTC", coverImage: "", deliverables: ["GitHub repository", "Preview URL", "README with integration notes"], reviewProcess: "Ninja Labs triage followed by Injective sponsor approval.", submissionMode: "direct", completionSteps: ["Build and test the widget", "Submit the repository and preview URL", "Receive sponsor approval"],
  },
  {
    slug: "wallet-onboarding-states", title: "Design a wallet onboarding flow", summary: "Create a clear wallet onboarding experience for new builders.", descriptionMarkdown: "Design a wallet onboarding flow that helps new builders understand each connection state. Account for success, failure, and recovery without making the first connection feel intimidating.", category: "Design", status: "active", reward: { amount: 300, currency: "USDC" }, sponsor: "Helix", deadline: "D-5", coverImage: "", deliverables: ["Annotated flow", "High-fidelity screens", "State and handoff notes"], reviewProcess: "Ninja Labs reviews the flow before Helix approves the final handoff.", submissionMode: "direct", completionSteps: ["Map onboarding states", "Prepare screens and annotations", "Submit the design handoff"],
  },
  {
    slug: "contract-security-audit", title: "Smart contract security audit", summary: "Review an Injective smart contract for security issues.", descriptionMarkdown: "Review an Injective smart contract for security issues and document findings with reproducible evidence. Focus on meaningful risks, practical remediation, and a report a sponsor can act on.", category: "Dev", status: "active", reward: { amount: 800, currency: "USDC" }, sponsor: "Ninja Labs", deadline: "D-12", coverImage: "", deliverables: ["Audit report", "Reproduction notes", "Remediation recommendations"], reviewProcess: "Ninja Labs validates findings and coordinates sponsor review.", submissionMode: "direct", completionSteps: ["Review the contract scope", "Document verified findings", "Submit the audit report"], applicationRequired: true, applicationTitle: "Smart contract audit for reward vault", applicationDescription: "Audit the CosmWasm reward vault before mainnet exposure. Applications are reviewed by the sponsor; approved applicants receive the audit scope and submit findings with reproducible evidence.",
  },
  {
    slug: "injective-dev-tutorial", title: "Write an Injective dev tutorial", summary: "Write an educational tutorial for the Injective developer community.", descriptionMarkdown: "Write an educational tutorial that helps Injective developers complete a useful task from start to finish. Use clear steps, accurate examples, and enough context for a new builder to follow along.", category: "Content", status: "active", reward: { amount: 250, currency: "INJ" }, sponsor: "Injective", deadline: "D-9", coverImage: "", deliverables: ["Tutorial draft", "Working code examples", "Published-ready markdown"], reviewProcess: "Ninja Labs checks technical accuracy before Injective editorial approval.", submissionMode: "direct", completionSteps: ["Choose the developer task", "Write and verify the tutorial", "Submit the draft and examples"],
  },
  {
    slug: "helix-volume-analytics", title: "Build a Helix volume analytics dashboard", summary: "Create a dashboard that makes Helix trading volume easy to explore.", descriptionMarkdown: "Create a dashboard that makes Helix trading volume easy to explore across useful time periods and markets. Prioritize legible data presentation and interactions that help users inspect changes.", category: "Dev", status: "active", reward: { amount: 600, currency: "USDC" }, sponsor: "Helix", deadline: "D-14", coverImage: "", deliverables: ["Source repository", "Deployed dashboard", "Data and setup notes"], reviewProcess: "Ninja Labs reviews implementation quality with Helix sponsor approval.", submissionMode: "direct", completionSteps: ["Build the dashboard", "Deploy and document the data", "Submit the project URL"],
  },
  {
    slug: "hydro-liquidity-explainer", title: "Create a Hydro liquidity explainer", summary: "Explain Hydro liquidity concepts for the Injective community.", descriptionMarkdown: "Explain Hydro liquidity concepts in language that Injective community members can use. Connect the core concepts to practical participation and make unfamiliar terms easy to understand.", category: "Content", status: "active", reward: { amount: 180, currency: "INJ" }, sponsor: "Hydro", deadline: "D-10", coverImage: "", deliverables: ["Explainer draft", "Supporting diagrams or examples", "Publication-ready copy"], reviewProcess: "Ninja Labs reviews clarity before Hydro approves publication.", submissionMode: "direct", completionSteps: ["Outline the concepts", "Create examples and supporting material", "Submit the final explainer"],
  },
  {
    slug: "neptune-api-docs", title: "Improve Neptune API documentation", summary: "Write clear, useful documentation for the Neptune API.", descriptionMarkdown: "Write clear, useful documentation for the Neptune API that helps developers make successful requests quickly. Improve navigation, examples, and explanations where implementation details are currently hard to discover.", category: "Content", status: "active", reward: { amount: 400, currency: "USDC" }, sponsor: "Neptune", deadline: "D-16", coverImage: "", deliverables: ["Documentation updates", "Verified request examples", "Change summary"], reviewProcess: "Ninja Labs verifies examples before Neptune approves the documentation.", submissionMode: "direct", completionSteps: ["Review the API documentation", "Write and verify updates", "Submit the change summary"],
  },
  {
    slug: "design-system-build", title: "Build a design system", summary: "Create a consistent design system for an Injective product.", descriptionMarkdown: "Create a consistent design system for an Injective product with reusable foundations and components. The completed work should make future product surfaces easier to build and maintain.", category: "Design", status: "closed", reward: { amount: 300, currency: "USDC" }, sponsor: "Ninja Labs", deadline: "Closed", coverImage: "", deliverables: ["Design foundations", "Component library", "Usage guidance"], reviewProcess: "Ninja Labs reviewed the system and approved the completed delivery.", submissionMode: "direct", completionSteps: ["Define foundations", "Build reusable components", "Complete sponsor review"],
  },
  {
    slug: "quest-copy-refresh", title: "Refresh quest copy", summary: "Refresh onboarding quest copy for a clearer builder experience.", descriptionMarkdown: "Refresh onboarding quest copy so builders understand each step and its value. Keep the voice direct, useful, and consistent across the quest experience.", category: "Content", status: "closed", reward: { amount: 120, currency: "INJ" }, sponsor: "Injective", deadline: "Closed", coverImage: "", deliverables: ["Updated quest copy", "Voice and terminology notes", "Change summary"], reviewProcess: "Ninja Labs and Injective approved the completed copy refresh.", submissionMode: "direct", completionSteps: ["Review the current journey", "Write the refreshed copy", "Complete editorial review"],
  },
];

export function getBounties(): Bounty[] { return bounties; }
export function getBounty(slug: string): Bounty | undefined { return bounties.find((bounty) => bounty.slug === slug); }
export function getActiveBounties(): Bounty[] { return bounties.filter((bounty) => bounty.status === "active"); }
